<Window x:Class="pyRevitUpdater.UpdaterWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
        Title="MainWindow"
        Height="325" Width="690" Margin="0"
        BorderThickness="0"
        Background="{x:Null}"
        WindowStartupLocation="CenterScreen"
        ScrollViewer.VerticalScrollBarVisibility="Disabled"
        HorizontalContentAlignment="Center"
        UseLayoutRounding="False"
        FontFamily="Courier New"
        AllowsTransparency="True"
        WindowStyle="None">
    <Window.Resources>
        <Color x:Key="pyRevitDarkColor">#2c3e50</Color>
        <Color x:Key="pyRevitAccentColor">#f39c12</Color>
        <SolidColorBrush x:Key="pyRevitDarkBrush"
                         Color="{StaticResource pyRevitDarkColor}"/>
        <SolidColorBrush x:Key="pyRevitAccentBrush"
                         Color="{StaticResource pyRevitAccentColor}"/>
        <Style TargetType="{x:Type TextBlock}">
            <Setter Property="Foreground"
                    Value="{StaticResource pyRevitDarkBrush}"/>
        </Style>
        <Style TargetType="{x:Type Button}">
            <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
            <Setter Property="Background" Value="{StaticResource pyRevitDarkBrush}"/>
            <Setter Property="BorderBrush" Value="#cccccc"/>
            <Setter Property="BorderThickness" Value="0"/>
            <Setter Property="Foreground" Value="White"/>
            <Setter Property="HorizontalContentAlignment" Value="Center"/>
            <Setter Property="VerticalContentAlignment" Value="Center"/>
            <Setter Property="Padding" Value="10,0,10,0"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type Button}">
                        <Border Name="Chrome"
                                Background="{TemplateBinding Background}"
                                BorderBrush="{TemplateBinding BorderBrush}"
                                BorderThickness="{TemplateBinding BorderThickness}"
                                CornerRadius="10"
                                Margin="2"
                                SnapsToDevicePixels="true">
                            <ContentPresenter Name="Presenter"
                                                      Margin="{TemplateBinding Padding}"
                                                      VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                                      HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                      RecognizesAccessKey="True"
                                                      SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"/>
                        </Border>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsMouseOver" Value="True">
                                <Setter Property="Background" Value="{StaticResource pyRevitAccentBrush}" />
                                <Setter Property="BorderBrush" Value="{StaticResource pyRevitAccentBrush}" />
                                <Setter Property="Foreground" Value="White" />
                            </Trigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Style TargetType="{x:Type ProgressBar}">
            <Setter Property="Background" Value="{StaticResource pyRevitDarkBrush}" />
            <Setter Property="Foreground" Value="{StaticResource pyRevitAccentBrush}" />
            <Setter Property="BorderBrush" Value="{x:Null}" />
            <Setter Property="BorderThickness" Value="0" />
            <Setter Property="Height" Value="10" />
            <Setter Property="IsTabStop" Value="False" />
            <Setter Property="Maximum" Value="100" />
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="ProgressBar">
                        <Grid x:Name="Root">
                            <Grid.OpacityMask>
                                <VisualBrush Visual="{Binding ElementName=PART_Track}" />
                            </Grid.OpacityMask>
                            <Border x:Name="PART_Track"
                                    CornerRadius="10"
                                    Background="{TemplateBinding Background}"
                                    BorderBrush="{TemplateBinding BorderBrush}"
                                    BorderThickness="{TemplateBinding BorderThickness}" />
                            <Grid x:Name="ProgressBarRootGrid">
                                <Grid x:Name="IndeterminateRoot" Visibility="Collapsed">
                                    <Rectangle x:Name="IndeterminateSolidFill"
                                               Margin="{TemplateBinding BorderThickness}"
                                               Fill="{StaticResource pyRevitAccentBrush}"
                                               Opacity="1"
                                               RenderTransformOrigin="0.5,0.5"
                                               StrokeThickness="0" />
                                    <Rectangle x:Name="IndeterminateGradientFill"
                                               Margin="{TemplateBinding BorderThickness}"
                                               Opacity=".2"
                                               StrokeThickness="1">
                                        <Rectangle.Fill>
                                            <LinearGradientBrush MappingMode="Absolute"
                                                                 SpreadMethod="Repeat"
                                                                 StartPoint="20,1" EndPoint="0,1">
                                                <LinearGradientBrush.Transform>
                                                    <TransformGroup>
                                                        <TranslateTransform x:Name="xTransform" X="0" />
                                                        <SkewTransform AngleX="-30" />
                                                    </TransformGroup>
                                                </LinearGradientBrush.Transform>
                                                <GradientStop Offset="0"
                                                              Color="{StaticResource pyRevitAccentColor}" />
                                                <GradientStop Offset="0.499"
                                                              Color="{StaticResource pyRevitAccentColor}" />
                                                <GradientStop Offset="0.500" Color="White"/>
                                                <GradientStop Offset="1.0" Color="White" />
                                            </LinearGradientBrush>
                                        </Rectangle.Fill>
                                    </Rectangle>
                                </Grid>
                                <Grid x:Name="DeterminateRoot">
                                    <Border x:Name="PART_Indicator"
                                            HorizontalAlignment="Left"
                                            Background="{StaticResource pyRevitAccentBrush}">
                                        <Rectangle x:Name="GradientFill"
                                               Opacity="0.7"
                                               Visibility="Collapsed">
                                            <Rectangle.Fill>
                                                <LinearGradientBrush MappingMode="Absolute"
                                                                     SpreadMethod="Repeat"
                                                                     StartPoint="20,1" EndPoint="0,1">
                                                    <LinearGradientBrush.Transform>
                                                        <TransformGroup>
                                                            <TranslateTransform X="0" />
                                                            <SkewTransform AngleX="-30" />
                                                        </TransformGroup>
                                                    </LinearGradientBrush.Transform>
                                                    <GradientStop Offset="0"
                                                                  Color="{StaticResource pyRevitAccentColor}" />
                                                    <GradientStop Offset="0.651"
                                                                  Color="{StaticResource pyRevitAccentColor}" />
                                                    <GradientStop Offset="0.093"
                                                                  Color="{StaticResource pyRevitAccentColor}" />
                                                    <GradientStop Offset="0.548"
                                                                  Color="{StaticResource pyRevitAccentColor}" />
                                                </LinearGradientBrush>
                                            </Rectangle.Fill>
                                        </Rectangle>
                                    </Border>
                                </Grid>
                                <TextBlock Text="{TemplateBinding Tag}"
                                           Foreground="White"
                                           FontSize="18"
                                           VerticalAlignment="Center"
                                           HorizontalAlignment="Center"/>
                            </Grid>
                            <VisualStateManager.VisualStateGroups>
                                <VisualStateGroup x:Name="CommonStates">
                                    <VisualState x:Name="Determinate" />
                                    <VisualState x:Name="Indeterminate">
                                        <Storyboard RepeatBehavior="Forever">
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="IndeterminateRoot"
                                                                       Storyboard.TargetProperty="(UIElement.Visibility)"
                                                                       Duration="00:00:00">
                                                <DiscreteObjectKeyFrame KeyTime="00:00:00">
                                                    <DiscreteObjectKeyFrame.Value>
                                                        <Visibility>Visible</Visibility>
                                                    </DiscreteObjectKeyFrame.Value>
                                                </DiscreteObjectKeyFrame>
                                            </ObjectAnimationUsingKeyFrames>
                                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="DeterminateRoot"
                                                                       Storyboard.TargetProperty="(UIElement.Visibility)"
                                                                       Duration="00:00:00">
                                                <DiscreteObjectKeyFrame KeyTime="00:00:00">
                                                    <DiscreteObjectKeyFrame.Value>
                                                        <Visibility>Collapsed</Visibility>
                                                    </DiscreteObjectKeyFrame.Value>
                                                </DiscreteObjectKeyFrame>
                                            </ObjectAnimationUsingKeyFrames>
                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetName="xTransform" Storyboard.TargetProperty="X">
                                                <SplineDoubleKeyFrame KeyTime="0" Value="0" />
                                                <SplineDoubleKeyFrame KeyTime="00:00:.35" Value="20" />
                                            </DoubleAnimationUsingKeyFrames>
                                        </Storyboard>
                                    </VisualState>
                                </VisualStateGroup>
                            </VisualStateManager.VisualStateGroups>
                        </Grid>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsMouseOver" Value="True">
                                <Setter Property="Background" Value="{StaticResource pyRevitAccentBrush}" />
                            </Trigger>
                            <Trigger Property="Orientation" Value="Vertical">
                                <Setter TargetName="Root" Property="LayoutTransform">
                                    <Setter.Value>
                                        <RotateTransform Angle="-90" />
                                    </Setter.Value>
                                </Setter>
                            </Trigger>
                            <Trigger Property="IsIndeterminate" Value="true">
                                <Setter TargetName="DeterminateRoot" Property="Visibility" Value="Collapsed" />
                                <Setter TargetName="IndeterminateRoot" Property="Visibility" Value="Visible" />
                            </Trigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Canvas x:Key="pyRevitLogo">
            <Canvas.Resources>
                <LinearGradientBrush x:Key="LogoDarkGradient"
                                     MappingMode="Absolute"
                                     StartPoint="155,173"
                                     EndPoint="-4,113">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#2C3E50" Offset="0"/>
                            <GradientStop Color="#2C3E50" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientA" MappingMode="Absolute" StartPoint="-9,107" EndPoint="126,116">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#F1C40F" Offset="0"/>
                            <GradientStop Color="#FFCF10" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientB" MappingMode="Absolute" StartPoint="129,276" EndPoint="179,101">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#F1C40F" Offset="0"/>
                            <GradientStop Color="#FFCF10" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                    <LinearGradientBrush.Transform>
                        <MatrixTransform Matrix="0.8407 0.5416 -0.5416 0.8407 82.663 -38.4394"/>
                    </LinearGradientBrush.Transform>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientC" MappingMode="Absolute" StartPoint="55,4" EndPoint="163,69">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#FFCF10" Offset="0"/>
                            <GradientStop Color="#F1C40F" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighLightGradientA" MappingMode="Absolute" StartPoint="139,130" EndPoint="31,60">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#00FFD633" Offset="0"/>
                            <GradientStop Color="#FFD633" Offset="0.9975"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighDarkGradientA" MappingMode="Absolute" StartPoint="135,167" EndPoint="-6,110">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#0034495E" Offset="0"/>
                            <GradientStop Color="#0B1014" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighDarkGradientB" MappingMode="Absolute" StartPoint="176,95" EndPoint="49,43">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#0034495E" Offset="0"/>
                            <GradientStop Color="#0B1014" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighLightGradientB" MappingMode="Absolute" StartPoint="68,28" EndPoint="145,19">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#00FFD633" Offset="0"/>
                            <GradientStop Color="#FFD633" Offset="0.9975"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
            </Canvas.Resources>
            <Polygon Points="0,140.3 121.8,218.4 172.9,161 22.3,65 "
                     Fill="{StaticResource LogoDarkGradient}"/>
            <Polygon Points="63,50.6 100,158.9 180.3,102.3 118.8,1 "
                     Fill="{StaticResource LogoDarkGradient}"/>
            <Polygon Points="21.5,65 181.5,102.3 100,158.9 -1,140.3 "
                     Fill="{StaticResource LogoLightGradientA}"/>
            <Polygon Points="122.4,166.2 198.1,132.8 121.8,219.5 "
                     Fill="{StaticResource LogoLightGradientB}"/>
            <Path Data="M185.7 58.8L118.8 0l-57 50.6l124.6 42.2L185.7 58.8z M150.3 64.8c-5.4 0-9.7-4.4-9.7-9.7  c0-5.4 4.4-9.7 9.7-9.7c5.4 0 9.7 4.4 9.7 9.7C160 60.5 155.6 64.8 150.3 64.8z"
                  Fill="{StaticResource LogoLightGradientC}"/>
            <Polygon Points="180.3,102.3 100,158.9 22.3,65 "
                     Fill="{StaticResource LogoHighLightGradientA}"/>
            <Polygon Points="0,140.3 0,140.3 109.3,187.1 137.3,138.3 133,135.6 100,158.9 "
                     Fill="{StaticResource LogoHighDarkGradientB}"/>
            <Polygon Points="61.8,50.6 167.7,96.1 168.5,86.7 "
                     Fill="{StaticResource LogoHighDarkGradientA}"/>
            <Polygon Points="155.1,31.8 118.8,0 61.8,50.6 "
                     Fill="{StaticResource LogoHighLightGradientB}"/>
        </Canvas>
    </Window.Resources>
    <Border CornerRadius="15" Margin="20,20,20,20">
        <Border.Effect>
            <DropShadowEffect Color="#FF2C3E50" BlurRadius="15" Opacity="0.25"/>
        </Border.Effect>
        <Border.Background>
            <SolidColorBrush Color="#fff"/>
        </Border.Background>
        <Grid Margin="20,20,20,20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="220"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <ContentControl Content="{StaticResource pyRevitLogo}"
                            Grid.Column="0"
                            Margin="20,10,0,0"
                            HorizontalAlignment="Left"
                            VerticalAlignment="Top">
                <ContentControl.LayoutTransform>
                    <ScaleTransform ScaleX="1"  ScaleY="1"/>
                </ContentControl.LayoutTransform>
            </ContentControl>
            <Grid Grid.Column="1">
                <StackPanel Margin="0,10,0,0">
                    <TextBlock x:Name="pyrevit_title"
                           VerticalAlignment="Top"
                           HorizontalAlignment="Center"
                           FontSize="44">
                    <Run Text="pyRevit"/><Run x:Name="short_version_info"
                                              FontSize="20"
                                              Text="v4.6"/>
                    </TextBlock>
                    <TextBlock x:Name="pyrevit_subtitle"
                           HorizontalAlignment="Center"
                           TextAlignment="Center"
                           TextWrapping="Wrap"
                           VerticalAlignment="Top"
                           FontSize="14"
                           Text="python tools for Autodesk Revit®"
                           LineHeight="20"/>
                </StackPanel>
                <StackPanel Margin="0,110,0,0"
                            HorizontalAlignment="Center">
                    <ProgressBar x:Name="UpdateButton" Value="0" IsIndeterminate="False"
                                 Width="320" Height="48" Tag="update" MouseUp="UpdateButton_MouseUp"/>
                    <!--<Button x:Name="CloseButton" Visibility="Visible"
                            Content="Close"
                            FontSize="14"
                            Width="150" Height="24"
                            Margin="0,5,0,0" Click="CloseButton_Click"/>-->
                </StackPanel>
                <StackPanel Margin="0,200,0,0">
                    <TextBlock x:Name="coded_with_love"
                               FontSize="14"
                               TextWrapping="Wrap"
                               VerticalAlignment="Bottom"
                               HorizontalAlignment="Center"
                               TextAlignment="Center"
                               Height="20">
                    <Run Text="&lt;/&gt; with"/>
                    <Run FontSize="17" Text="♥"/>
                    <Run Text="in ['pdx', 'hio', 'rno']"/>
                    <LineBreak/>
                    </TextBlock>
                    <TextBlock Text="© 2014-2018 Ehsan Iran-Nejad"
                               TextAlignment="Center"
                               HorizontalAlignment="Center"/>
                </StackPanel>
            </Grid>
        </Grid>
    </Border>
</Window>
